config/routes.rb
Rails.application.routes.draw do
  
  resources :levels
  resources :tour_package_reservations
  post 'auth/verify' => 'omniauth_verifications#verify_token'
  
  resources :service_restaurants
  resources :flights
  resources :airlines
  resources :places
  resources :hotels do
    get 'rooms'
  end
  
  resources :rooms
  resources :restaurants
  resources :tour_packages
  devise_for :users, :controllers => {:sessions => "sessions"}
  
  get 'pages/index'

  get 'pages/home'

  get 'pages/tour_package'

  get 'pages/flight'

  get 'pages/hotel'

  get 'pages/restaurant'

  get 'pages/contact_us'

  get 'pages/sign_in'

  root 'pages#home'
  

end

app/models/airline.rb
class Airline < ActiveRecord::Base
    has_many:flights
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    
    before_create :generate_access_token
    
private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex 
        end while self.class.exists?(access_token: access_token)
    end
    
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airline

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :location
  has_many :rooms
  
  validates :name, presence: true
  validates :starts, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :pictureUrl, presence: true
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :service_restaurants
    
  validates :name, presence: true
  validates :description, presence: true
  validates :level, presence: true
  validates :websiteurl, presence: true
  validates :logourl, presence: true
  validates :status, presence: true
  validates :pictureUrl, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
end

app/models/service_restaurant.rb
class ServiceRestaurant < ActiveRecord::Base
    belongs_to :restaurant
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/tour_package.rb
class TourPackage < ActiveRecord::Base
  belongs_to :flight
  belongs_to :hotel
  belongs_to :restaurant
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
         
  def self.find_for_verfied_token_response(auth)
    user = User.where(:provider => "google_oauth2", :uid => auth[:id]).first
  
    unless user
      puts("gotraavel user create")
      user = User.create(:name => auth[:name],
                         :email => auth[:email],
                         :provider => "google_oauth2",
                         :uid => auth[:id])
      puts("gotraavel apikey create")
      user.api_key = ApiKey.create!
    end
  
    user
  end
end

app/controllers/tour_packages_controller.rb
class TourPackagesController < ApplicationController
  before_action :set_tour_package, only: [:show, :edit, :update, :destroy]
  layout "appadmin"
  # GET /tour_packages
  # GET /tour_packages.json
  def index
    @tour_packages = TourPackage.all
  end

  # GET /tour_packages/1
  # GET /tour_packages/1.json
  def show
  end

  # GET /tour_packages/new
  def new
    @tour_package = TourPackage.new
  end

  # GET /tour_packages/1/edit
  def edit
  end

  # POST /tour_packages
  # POST /tour_packages.json
  def create
    @tour_package = TourPackage.new(tour_package_params)

    respond_to do |format|
      if @tour_package.save
        format.html { redirect_to @tour_package, notice: 'Tour package was successfully created.' }
        format.json { render :show, status: :created, location: @tour_package }
      else
        format.html { render :new }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_packages/1
  # PATCH/PUT /tour_packages/1.json
  def update
    respond_to do |format|
      if @tour_package.update(tour_package_params)
        format.html { redirect_to @tour_package, notice: 'Tour package was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour_package }
      else
        format.html { render :edit }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_packages/1
  # DELETE /tour_packages/1.json
  def destroy
    @tour_package.destroy
    respond_to do |format|
      format.html { redirect_to tour_packages_url, notice: 'Tour package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_package
      @tour_package = TourPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_package_params
      params.require(:tour_package).permit(:flight_id, :hotel_id, :restaurant_id, :place_id, :title, :picture_url, :description)
    end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tour_packages_helper.rb
module TourPackagesHelper
end

app/views/tour_packages/_form.html.erb
<%= simple_form_for(@tour_package) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :flight, :label_method => lambda { |r| "#{r.origin_country}-#{r.origin_state}-#{r.origin_city} to #{r.destination_country}-#{r.destination_state}-#{r.destination_city} " } %>
    <%= f.association :hotel %>
    <%= f.association :restaurant %>
    <%= f.association :place %>
    <%= f.input :title %>
    <%= f.input :picture_url %>
    <%= f.input :description %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tour_packages/edit.html.erb
<h1>Editing Tour Package</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour_package %> |
<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/index.html.erb
<%- model_class = TourPackage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:origin ) %></th>
      <th><%= model_class.human_attribute_name(:destination ) %></th>
      <th><%= model_class.human_attribute_name(:departure ) %></th>
      <th><%= model_class.human_attribute_name(:returning ) %></th>
      <th><%= model_class.human_attribute_name(:Hotel) %></th>
      <th><%= model_class.human_attribute_name(:Restaurant) %></th>
      <th><%= model_class.human_attribute_name(:Place) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:picture_url) %></th>
      <th><%= model_class.human_attribute_name(:desccription) %></th>
     
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>
  </thead>
  <tbody>
    <% @tour_packages.each do |tour_package| %>
      <tr>
        <td><%= link_to tour_package.id, tour_package_path(tour_package) %></td>
        <td><%= tour_package.flight.origin_country %>-<%= tour_package.flight.origin_state %>-<%= tour_package.flight.origin_city %></td>
        <td><%= tour_package.flight.destination_country %>-<%= tour_package.flight.destination_state %>-<%= tour_package.flight.destination_city %></td>
       
        <td><%= tour_package.flight.departure %></td>
        <td><%= tour_package.flight.returning %></td>
        <td><%= tour_package.hotel.name %></td>
        <td><%= tour_package.restaurant.name %></td>
        <td><%= tour_package.place.name %></td>
         <td><%= tour_package.title %></td>
        <td><%= tour_package.picture_url %></td>
        <td><%= tour_package.description %></td>
       
    
        <td>
         
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      tour_package, :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tour_package_path(tour_package), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tour_package_path(tour_package),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tour_package_path,
            :class => 'btn btn-primary' %>

app/views/tour_packages/new.html.erb
<h1>New Tour Package</h1>

<%= render 'form' %>

<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @tour_package.flight.origin_country %>
  <%= @tour_package.flight.origin_state %>
  <%= @tour_package.flight.origin_city %>
  </p>
<p>
  <strong>Destination:</strong>
  <%= @tour_package.flight.destination_country %>
  <%= @tour_package.flight.destination_state %>
  <%= @tour_package.flight.destination_city %>
  </p>
<p>
  <strong>Departure:</strong>
  <%= @tour_package.flight.departure %>
  </p>
<p>
  <strong>Returning:</strong>
  <%= @tour_package.flight.returning %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @tour_package.hotel.name %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @tour_package.restaurant.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @tour_package.place.name %>
</p>

<%= link_to 'Edit', edit_tour_package_path(@tour_package) %> |
<%= link_to 'Back', tour_packages_path %>