config/routes.rb
Rails.application.routes.draw do
  
  resources :levels
  resources :tour_package_reservations
  post 'auth/verify' => 'omniauth_verifications#verify_token'
  
  resources :service_restaurants
  resources :flights
  resources :airlines
  resources :places
  resources :hotels do
    get 'rooms'
  end
  
  resources :rooms
  resources :restaurants
  resources :tour_packages
  devise_for :users, :controllers => {:sessions => "sessions"}
  
  get 'pages/index'

  get 'pages/home'

  get 'pages/tour_package'

  get 'pages/flight'

  get 'pages/hotel'

  get 'pages/restaurant'

  get 'pages/contact_us'

  get 'pages/sign_in'

  root 'pages#home'
  

end

app/models/airline.rb
class Airline < ActiveRecord::Base
    has_many:flights
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    
    before_create :generate_access_token
    
private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex 
        end while self.class.exists?(access_token: access_token)
    end
    
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airline

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :location
  has_many :rooms
  
  validates :name, presence: true
  validates :starts, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :pictureUrl, presence: true
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :service_restaurants
    
  validates :name, presence: true
  validates :description, presence: true
  validates :level, presence: true
  validates :websiteurl, presence: true
  validates :logourl, presence: true
  validates :status, presence: true
  validates :pictureUrl, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
end

app/models/service_restaurant.rb
class ServiceRestaurant < ActiveRecord::Base
    belongs_to :restaurant
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/tour_package.rb
class TourPackage < ActiveRecord::Base
  belongs_to :flight
  belongs_to :hotel
  belongs_to :restaurant
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
         
  def self.find_for_verfied_token_response(auth)
    user = User.where(:provider => "google_oauth2", :uid => auth[:id]).first
  
    unless user
      puts("gotraavel user create")
      user = User.create(:name => auth[:name],
                         :email => auth[:email],
                         :provider => "google_oauth2",
                         :uid => auth[:id])
      puts("gotraavel apikey create")
      user.api_key = ApiKey.create!
    end
  
    user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  layout "appadmin"

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_type, :description, :number_people, :price, :hotel_id)
    end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :room_type %>
    <%= f.input :description %>
    <%= f.input :number_people %>
    <%= f.input :price %>
    <%= f.association :hotel %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:room_type) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:number_people) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:hotel) %></th>
      <!--<th><%=t '.actions', :default => t("helpers.actions") %></th>-->
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.id, room_path(room) %></td>
        <td><%= room.name %></td>
        <td><%= room.room_type %></td>
        <td><%= room.description %></td>
        <td><%= room.number_people %></td>
        <td><%= room.price %></td>
        <td><%= room.hotel.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      room, :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_room_path(room), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      room_path(room),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_room_path,
            :class => 'btn btn-primary' %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Number people:</strong>
  <%= @room.number_people %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>