config/routes.rb
Rails.application.routes.draw do
  
  resources :levels
  resources :tour_package_reservations
  post 'auth/verify' => 'omniauth_verifications#verify_token'
  
  resources :service_restaurants
  resources :flights
  resources :airlines
  resources :places
  resources :hotels do
    get 'rooms'
  end
  
  resources :rooms
  resources :restaurants
  resources :tour_packages
  devise_for :users, :controllers => {:sessions => "sessions"}
  
  get 'pages/index'

  get 'pages/home'

  get 'pages/tour_package'

  get 'pages/flight'

  get 'pages/hotel'

  get 'pages/restaurant'

  get 'pages/contact_us'

  get 'pages/sign_in'

  root 'pages#home'
  

end

app/models/airline.rb
class Airline < ActiveRecord::Base
    has_many:flights
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    
    before_create :generate_access_token
    
private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex 
        end while self.class.exists?(access_token: access_token)
    end
    
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airline

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :location
  has_many :rooms
  
  validates :name, presence: true
  validates :starts, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :pictureUrl, presence: true
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    has_many :service_restaurants
    
  validates :name, presence: true
  validates :description, presence: true
  validates :level, presence: true
  validates :websiteurl, presence: true
  validates :logourl, presence: true
  validates :status, presence: true
  validates :pictureUrl, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
end

app/models/service_restaurant.rb
class ServiceRestaurant < ActiveRecord::Base
    belongs_to :restaurant
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/tour_package.rb
class TourPackage < ActiveRecord::Base
  belongs_to :flight
  belongs_to :hotel
  belongs_to :restaurant
  belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
         
  def self.find_for_verfied_token_response(auth)
    user = User.where(:provider => "google_oauth2", :uid => auth[:id]).first
  
    unless user
      puts("gotraavel user create")
      user = User.create(:name => auth[:name],
                         :email => auth[:email],
                         :provider => "google_oauth2",
                         :uid => auth[:id])
      puts("gotraavel apikey create")
      user.api_key = ApiKey.create!
    end
  
    user
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :description)
    end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/levels/_form.html.erb
<%= simple_form_for(@level) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.description %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @level.description %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>